### PR TITLE
Support alternate note-off message

### PR DESCRIPTION
**Pull request by jpursell**

### CODE REVIEW

**Comment by jpursell** [comment]
I have an old evolution MK-249C that sends a Note-On with velocity 0 message when you let off the key. I also have a newer MPK mini that sends a proper Note-Off message. I checked that they both work with this small change.

**Comment by gjf2a** [comment]
Great, thank you for your contribution!

**Comment by gjf2a** [comment]
I've [published the change to crates.io as version 0.2.1](https://crates.io/crates/midi_fundsp/0.2.1). Thanks again for your contribution!

**Comment by jpursell** [comment]
Happy to help

**Pull request merged**
